#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-DHCP-Control
version:      0.09
version_from: lib/Net/DHCP/Control.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
